name: Build Fundo WebApi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '6.0.x'

      # - name: Restore dependencies
      #   working-directory: backend/src
      #   run: dotnet restore

      # - name: Run unit tests
      #   working-directory: backend/src
      #   run: dotnet test --no-restore --verbosity normal

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        working-directory: backend/src
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        working-directory: backend/src
        run: |
          docker-compose ps
          sleep 10

      - name: Run tests inside container
        run: docker-compose exec loan-management-api dotnet test --verbosity normal

      - name: Show logs
        working-directory: backend/src
        run: docker-compose logs

      - name: Tear down
        if: always()
        working-directory: backend/src
        run: docker-compose down