name: Build Fundo WebApi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        working-directory: backend/src
        run: dotnet restore

      - name: Build
        working-directory: backend/src
        run: dotnet build --no-restore

      - name: Test
        working-directory: backend/src
        run: dotnet test --no-build --verbosity normal

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        working-directory: backend/src
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        working-directory: backend/src
        run: |
          docker-compose ps
          sleep 5