name: Build Fundo WebApi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o out

      - name: Build and run Docker Compose
        working-directory: backend/src
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        working-directory: backend/src
        run: |
          docker-compose ps
          sleep 5

      - name: Run tests
        working-directory: backend/src
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=Fundo;User=sa;Password=pwd123456@;TrustServerCertificate=True;"
        run: dotnet test Fundo.Services.Tests/Fundo.Services.Tests.csproj --no-build --verbosity detailed